# This is a basic workflow to help you get started with Actions

name: CI_Permission

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      ALLOWED_USERS: ${{ secrets.ALLOWED_USERS }}

    steps:
      - name: Check if actor is allowed
        run: |
          allowed_users="${{ env.ALLOWED_USERS }}"
          IFS=',' read -ra USERS <<< "$allowed_users"
          actor="${{ github.actor }}"
          is_allowed=false
          for user in "${USERS[@]}"; do
            if [[ "$user" == "$actor" ]]; then
              is_allowed=true
              break
            fi
          done
          if [[ "$is_allowed" == "false" ]]; then
            echo "User $actor is not allowed to run this job."
            exit 1
          fi

    # Steps represent a sequence of tasks that will be executed as part of the job
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
